---
name: ReallyCheat
main: hachkingtohach1\reallycheat\RCAPIProvider
author: hachkingtohach1(DragoVN)
api: 5.3.0
version: 2.1.5

commands:
  reallycheat:
    permission: reallycheat.command
  rc:
    permission: reallycheat.command
permissions:
  reallycheat.command:
    description: "Permission to use the ReallyCheat command."
    default: false
...
